AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Core API
      FailOnWarnings : true

      LambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    Action: lambda:invokeFunction
    FunctionName: !GetAtt [ApiGateway, Arn]
    Principal: apigateway.amazonaws.com
    SourceArn: !Join
      - ''
      - - 'arn:aws:execute-api:'
      - - !Ref 'AWS::Region'
      - - ':'
      - - !Ref 'AWS::AccountId'
      - - ':'
      - - !Ref 'ApiGateway'
      - - "/*"
